### ISSUE TITLE
2018.2.2 执行报一个错gevent SSLError

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/IAmInPactera#26]
执行后，用http访问报一个错gevent SSLError

**Comment by vieyahn2017** [comment]
gevent SSLError

**Comment by vieyahn2017** [comment]
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:48:16 2018 <Greenlet at 0x803f260: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x8043950 fileno=[Errno 9] Bad file de)> failed
 with SSLError

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:48:16 2018 <Greenlet at 0x7fd7e40: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x805bef0 fileno=[Errno 9] Bad file de)> failed
 with SSLError

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:48:16 2018 <Greenlet at 0x803f260: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x8043950 fileno=[Errno 9] Bad file de)> failed
 with SSLError

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:48:16 2018 <Greenlet at 0x803f260: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x8043a10 fileno=[Errno 9] Bad file de)> failed
 with SSLError

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:48:21 2018 <Greenlet at 0x803f260: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x8043ab0 fileno=[Errno 9] Bad file de)> failed
 with SSLError

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:48:51 2018 <Greenlet at 0x803f260: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x8043950 fileno=[Errno 9] Bad file de)> failed
 with SSLError

KeyboardInterrupt
Tue Jan 30 09:49:44 2018
Traceback (most recent call last):
  File "dm_main.py", line 17, in <module>
    WSGIServer(('0.0.0.0', args.manage_port), dm_app, keyfile='cakey_nopass.pem'
, certfile='cacert.pem').serve_forever()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 362, in serve_
forever
    self._stop_event.wait()
  File "C:\Python27\lib\site-packages\gevent\event.py", line 219, in wait
    return self._wait(timeout)
  File "C:\Python27\lib\site-packages\gevent\event.py", line 129, in _wait
    gotit = self._wait_core(timeout)
  File "C:\Python27\lib\site-packages\gevent\event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
KeyboardInterrupt

C:\Users\ywx536122\Downloads\gitlab_codes\Dataprotect_Simu\DJ_simu_9000\oceansto
r_9000>python db.py -i=8.46.186.126

C:\Users\ywx536122\Downloads\gitlab_codes\Dataprotect_Simu\DJ_simu_9000\oceansto
r_9000>python dm_main.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:50:21 2018 <Greenlet at 0x7f3c3a0: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x7f6bcb0 fileno=[Errno 9] Bad file de)> failed
 with SSLError

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:50:21 2018 <Greenlet at 0x7f3c3a0: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x7f6bbf0 fileno=[Errno 9] Bad file de)> failed
 with SSLError

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:50:21 2018 <Greenlet at 0x7f3c3a0: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x7f6bc50 fileno=[Errno 9] Bad file de)> failed
 with SSLError

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:51:21 2018 <Greenlet at 0x7f3c3a0: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x7f6bcb0 fileno=[Errno 9] Bad file de)> failed
 with SSLError

KeyboardInterrupt
Tue Jan 30 09:56:17 2018
Traceback (most recent call last):
  File "dm_main.py", line 17, in <module>
    WSGIServer(('0.0.0.0', args.manage_port), dm_app, keyfile='cakey_nopass.pem'
, certfile='cacert.pem').serve_forever()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 362, in serve_
forever
    self._stop_event.wait()
  File "C:\Python27\lib\site-packages\gevent\event.py", line 219, in wait
    return self._wait(timeout)
  File "C:\Python27\lib\site-packages\gevent\event.py", line 129, in _wait
    gotit = self._wait_core(timeout)
  File "C:\Python27\lib\site-packages\gevent\event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
KeyboardInterrupt

C:\Users\ywx536122\Downloads\gitlab_codes\Dataprotect_Simu\DJ_simu_9000\oceansto
r_9000>python db.py
usage: db [-h] -i MANAGE_IP [-p MANAGE_PORT] [-w SWIFT_PORT] [-s S3_PORT]
          [-v VERSION]
db: error: argument -i/--manage_ip is required

C:\Users\ywx536122\Downloads\gitlab_codes\Dataprotect_Simu\DJ_simu_9000\oceansto
r_9000>python db.py -i
usage: db [-h] -i MANAGE_IP [-p MANAGE_PORT] [-w SWIFT_PORT] [-s S3_PORT]
          [-v VERSION]
db: error: argument -i/--manage_ip: expected one argument

C:\Users\ywx536122\Downloads\gitlab_codes\Dataprotect_Simu\DJ_simu_9000\oceansto
r_9000>python db.py -i=127.0.0.1

C:\Users\ywx536122\Downloads\gitlab_codes\Dataprotect_Simu\DJ_simu_9000\oceansto
r_9000>python dm_main.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 26, in _handle
_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 174, in wrap_socke
t_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 695, in wrap_s
ocket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 270, in __init
__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
Tue Jan 30 09:58:05 2018 <Greenlet at 0x7f3c3a0: _handle_and_close_when_done(<bo
und method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_clo
se of <WSGIServer a, (<socket at 0x7f6bcd0 fileno=[Errno 9] Bad file de)> failed
 with SSLError

127.0.0.1 - - [2018-01-30 10:19:56] "GET / HTTP/1.1" 200 1163 0.027000
127.0.0.1 - - [2018-01-30 10:19:56] "GET /css/style.css HTTP/1.1" 200 782 0.0090
00
127.0.0.1 - - [2018-01-30 10:19:56] "GET /images/logo.png HTTP/1.1" 200 20769 0.
026000
127.0.0.1 - - [2018-01-30 10:19:56] "GET /favicon.ico HTTP/1.1" 404 565 0.083000

127.0.0.1 - - [2018-01-30 10:21:25] "GET /devicemanager/rest HTTP/1.1" 404 565 0
.007000
127.0.0.1 - - [2018-01-30 10:21:25] "GET /css/style.css HTTP/1.1" 200 782 0.0060
00
127.0.0.1 - - [2018-01-30 10:22:59] "GET /deviceManager HTTP/1.1" 404 565 0.0100
00
127.0.0.1 - - [2018-01-30 10:22:59] "GET /css/style.css HTTP/1.1" 200 782 0.0070
00

**Comment by vieyahn2017** [comment]
有人这么说

d | This is a gevent bug: https://groups.google.com/forum/#!searchin/gevent/ssl/gevent/olkwX4jUUlU/_OJECy1ppYIJfix it installing last one version ( gevent-1.1rc5 )sudo pip install --pre gevent --upgrade The last one is Release Candidate, then you need --pre argument. https://groups.google.com/forum/#!topic/gevent/5mXt5w2kukEshare\|improve this answeranswered Mar 3 '16 at 4:36Rui Martins421816 | share\|improve this answer | answered Mar 3 '16 at 4:36Rui Martins421816
-- | -- | -- | --
share\|improve this answer | answered Mar 3 '16 at 4:36Rui Martins421816
  | 1Yes, it's a bug for gevent, also see github.com/gevent/gevent/issues/477. – Peter Pan Mar 3 '16 at 6:36add a comment \|

**Comment by vieyahn2017** [comment]
https://github.com/gevent/gevent/issues/477

**Comment by vieyahn2017** [comment]
那份代码运行后，浏览器用http访问会报错。
网上搜，说是gevent在python2.7.9的bug

**Comment by vieyahn2017** [comment]
https能访问，也就没纠结这个了

**Comment by vieyahn2017** [comment]
2.6号测试发现是因为：

WSGIServer(('0.0.0.0', args.manage_port), dm_app).serve_forever()   
这样写用http访问   
WSGIServer(('0.0.0.0', args.manage_port), dm_app, keyfile='cakey_nopass.pem', certfile='cacert.pem').serve_forever()   
这样写就用https访问
